high_score:
  name: null
  score: 0
max_time: 5
player:
  name: Tasnim
  score: 0
words:
  - CLIMATE
  - PYTHON
  - GITHUB
  - GREEN
  - GAME
  - ENERGY
  - PEACE
  - JAVASCRIPT
  - PROCESSOR
  - GOOGLE
  - MICROSOFT
  - AMAZON
  - PERFORMANCE
  - PUZZLE
  - CINEMA
  - SOLAR
  - APPLE
  - RESISTOR
  - SMARTPHONE
words_count: 13
